name: magnifier
description: A Flutter plackage that a Magnifying Glass to your App.
version: 0.0.3
repository: https://github.com/preetjdp/magnifier
# homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
